### ISSUE TITLE
Segfault when built without AVX

### ISSUE THREAD

**Issue by jeremyrgreen** [RJHudspith/KQED#1]
The test program KQED fails with a segfault when it is built without AVX:
```
Program received signal SIGSEGV, Segmentation fault.
accessv (flag_hy=false, use_y_derivs=true, ix=36, iy=141118755, nm=QG0, ndy=false, ndcb=d1cb, cb=-0.49999999999791633, y=0.10000000000041638, Grid=...) at LIBFILES/getff-new.c:173
173	  const double y1 = Grid.YY[iy];
```
Here's the backtrace:
```
#0  accessv (flag_hy=false, use_y_derivs=true, ix=36, iy=141118755, nm=QG0, 
    ndy=false, ndcb=d1cb, cb=-0.49999999999791633, y=0.10000000000041638, 
    Grid=...) at LIBFILES/getff-new.c:173
#1  0x0000000000451a4a in extractff (nm=QG0, ndy=false, ndcb=d1cb, Inv=..., 
    Grid=..., PC=0x0) at LIBFILES/getff-new.c:243
#2  0x0000000000452070 in extractff2 (nm=QG0, ndcb=d0cb, Inv=..., Grid=..., 
    PC=0x0, F=0x7fffffffb790) at LIBFILES/getff-new.c:308
#3  0x000000000044d9b9 in chnr_dS (xv=0x7fffffffc300, yv=0x7fffffffc320, 
    Inv=..., Grid=..., PC=0x0, dxv=0x7fffffffbb40, dyv=0x7fffffffbb60)
    at LIBFILES/chnr_dS.c:68
#4  0x000000000042f795 in init_STV (xv=0x7fffffffc300, yv=0x7fffffffc320, 
    t=..., k=0x7fffffffbb40) at LIBFILES/QED_kernel.c:514
#5  0x000000000042fc0b in kernelQED (xv=0x7fffffffc300, yv=0x7fffffffc320, 
    t=..., kerv=0x7fffffffc340) at LIBFILES/QED_kernel.c:533
#6  0x000000000041d344 in QED_kernel_L0 (xv=0x7fffffffc300, yv=0x7fffffffc320, 
    t=..., kerv=0x7fffffffc340) at LIBFILES/kernels.c:112
#7  0x00000000004028e6 in example4 (t=...) at amu_forlattice.c:224
#8  0x000000000040dcb9 in main () at amu_forlattice.c:1456
```
It looks like `Inv.INVy.idx` is uninitialized.

**Comment by RJHudspith** [comment]
It certainly does look like that, the index is not right. Let me check.
